import Navigation from "@/components/Navigation";
import Head from "next/head";

export default function Layout({ children, metaTitle, metaDesc }) {
  return (
    <>
      <Head>
        <title>{`${metaTitle || "App NextJS"}`}</title>
        <meta
          name="description"
          content={`${metaDesc || "Generated by create next app"}`}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: "1rem" }}>
        <Navigation />
        {children}
      </main>
    </>
  );
}
